services:
  python:
    image: python:3.12-slim
    container_name: python
    volumes:
      - .python:/app
    tty: true # memastikan komponennya tetap berjalan karena beberapa image akan berhenti jika tidak ada perintah yang dijalankan
    networks:
      - docker_network

networks:
  docker_network:
    driver: bridge
